---
- name: "Installation Elastic on SRV"
  hosts: srv
  gather_facts: false
  tasks:
    - name: "Download Elastic Agent"
      win_shell: |
        Invoke-WebRequest -Uri https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.9.0-windows-x86_64.zip -OutFile elastic-agent-8.9.0-windows-x86_64.zip
      args:
        executable: powershell.exe

    - name: "Extract Elastic Agent Archive"
      win_shell: |
        Expand-Archive .\elastic-agent-8.9.0-windows-x86_64.zip -DestinationPath .
      args:
       executable: powershell.exe

    - name: "Install Elastic Agent"
      win_shell: |
        .\elastic-agent-8.9.0-windows-x86_64\elastic-agent.exe install --url=https://10.202.0.192:8220 --enrollment-token=YU9UcEVJd0JLSnRGUVB1OHdGVko6M0EzeC1rWU9RZmFiczBWZGJMeUxhZw== --insecure -f
      args:
        executable: powershell.exe
# Le -f est pour bypass de Y à founir dans la commande. 
# Le --insecure est pour bypass l'erreur de certificat.